language: scala
scala:
 - 2.11.6
jdk:
 - openjdk7
 - oraclejdk7
 - oraclejdk8
script:
 - sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
 - sbt ++$TRAVIS_SCALA_VERSION coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a22ea519223977cc7fc9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
